apiVersion: v1
kind: Service
metadata:
  name: argoproj-demo-stable
spec:
  type: ClusterIP
  selector:
    app: argoproj-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: argoproj-demo-canary
spec:
  type: ClusterIP
  selector:
    app: argoproj-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argoproj-demo
spec:
  selector:
    matchLabels:
      app: argoproj-demo
  replicas: 4
  template:
    metadata:
      labels:
        app: argoproj-demo
    spec:
      serviceAccountName: tsubauaaa-dev
      containers:
        - name: argoproj-demo
          image: argoproj/rollouts-demo:blue
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            preriodSeconds: 5
          readnessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            preriodSeconds: 5
          resources:
            requests:
              memory: 84Mi
              cpu: 100m
            limits:
              memory: 84Mi
              cpu: 100m
  strategy:
    canary:
      canaryService: argoproj-demo-canary
      stableService: argoproj-demo-stable
      trafficRouting:
        managedRoutes:
          - name: set-header-1
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoutes: 
              - name: tsubauaaa-dev
                useHeaderRoutes: true
            namespace: default
      steps:
        - setWeight: 50
        - setHeaderRoute:
            name: "set-header-1"
            match:
              - headerName: X-Canary
                headerValue:
                  exact: "true"
        - pause: {}
        - setWeight: 100
        - pause: {}