apiVersion: argoproj.io/v1alpha1  # Changed from apps/v1
kind: Rollout                     # Changed from Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - name: guestbook-ui
          image: argoproj/rollouts-demo:blue
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  strategy:
    canary:
      canaryService: guestbook-ui-canary
      stableService: guestbook-ui-stable
      # trafficRouting:
      #   plugins:
      #     argoproj-labs/gatewayAPI:
      #       httpRoute: guestbook-ui-httproute # our created httproute
      #       namespace: default # namespace where this rollout resides
      steps:
        - setWeight: 25
        - pause: { duration: 10s }
        - setWeight: 50
        - pause: { duration: 10s }
        - setWeight: 75
        - pause: { duration: 10s }
        - setWeight: 100
      # maxSurge: 100%                # 新バージョンのPod数を旧バージョンのPod数に追加（最大で倍のPod数が稼働）
      # maxUnavailable: 0             # 旧バージョンのPod数は減らさない
