# apiVersion: apps/v1
apiVersion: argoproj.io/v1alpha1  # Changed from apps/v1
# kind: Deployment
kind: Rollout                     # Changed from Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
      # - image: nginx:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    canary:                        # Changed from rollingUpdate or recreate
      steps:
        - setWeight: 25
        - pause: {}
        - setWeight: 50
        - pause: {}
        - setWeight: 75
        - pause: {}
        - setWeight: 100